### list

POST http://localhost:5000/post-endpoint
Content-Type: application/json
#Accept: application/cbor

{
  "Hello": "mushtaq"
}

###

POST http://localhost:5000/post-endpoint
Content-Type: application/json
#Accept: application/cbor

{
  "RandomBag": {}
}

###
